##spring:
##  datasource:
##    url: jdbc:mysql://localhost:3306/testeing
##    username: testuser
##    password: 123456
##  jpa:
##    show-sql: true
##    hibernate:
##      ddl-auto: create
##    properties:
##      hibernate:
##      dialect: org.hibernate.dialect.MySQL8Dialect

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect